version: '3.8'

services:
  db:
    image: postgres:16
    container_name: marcus_postgres
    restart: always
    environment:
      POSTGRES_DB: marcusbike
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: marcus_api
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marcusbike
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata:
